{"name": "Проверяем что невозможно авторизоваться при отправке некорректных данных.", "status": "passed", "steps": [{"name": "Авторизация курьера", "status": "passed", "parameters": [{"name": "login", "value": "'qeuisgdlsh'"}, {"name": "password", "value": "'incorrect_data'"}], "start": 1734183810709, "stop": 1734183810872}], "parameters": [{"name": "field_name", "value": "'password'"}], "start": 1734183810709, "stop": 1734183810872, "uuid": "433e3042-a222-40e7-930d-4adcacf8e9d8", "historyId": "66f7a12462bba69a3e33bba9023cb676", "testCaseId": "e19d5f6ce864d2e906838d7c7da07064", "fullName": "tests.tests_courier.test_courier_login.TestLoginCourier#test_login_courier_with_incorrect_login_or_password", "labels": [{"name": "parentSuite", "value": "tests.tests_courier"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "172.31.52.44-vpn.dhcp.yndx.net"}, {"name": "thread", "value": "18169-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_courier.test_courier_login"}]}